//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardPage
    {
        public int CardPageId { get; set; }
        public int PatientCardId { get; set; }
        public int PageNumber { get; set; }
        public System.DateTime Date { get; set; }
        public string Complaints { get; set; }
        public string Diagnosis { get; set; }
        public string Treatment { get; set; }
        public int DoctorId { get; set; }
    
        public virtual PatientCard PatientCard { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
