//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictSchedule
    {
        public int DistrictScheduleId { get; set; }
        public int SurgeryId { get; set; }
        public int DoctorId { get; set; }
        public System.DateTime ReceiptDate { get; set; }
    
        public virtual Surgery Surgery { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
