//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.CardPages = new HashSet<CardPage>();
            this.DistrictSchedule = new HashSet<DistrictSchedule>();
            this.SiteDoctors = new HashSet<SiteDoctors>();
        }
    
        public int DoctorId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patrynum { get; set; }
        public int SpecialId { get; set; }
        public int CategoryId { get; set; }
        public int Expirience { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Icon { get; set; }
        public int DoctorTypeId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Special Special { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardPage> CardPages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistrictSchedule> DistrictSchedule { get; set; }
        public virtual DoctorType DoctorType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteDoctors> SiteDoctors { get; set; }
    }
}
